# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoactl" do
  name "stoactl"
  desc "GitOps-native CLI for STOA Platform"
  homepage "https://gostoa.dev"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoactl"

  on_macos do
    on_intel do
      url "https://github.com/stoa-platform/stoactl/releases/download/v#{version}/stoactl_#{version}_darwin_amd64.tar.gz"
      sha256 "f63bf1779a31ab2f1c67e2d9afa5de335438526cf9cc4d834058bb515fd39d19"
    end
    on_arm do
      url "https://github.com/stoa-platform/stoactl/releases/download/v#{version}/stoactl_#{version}_darwin_arm64.tar.gz"
      sha256 "aca27f0b06f42016c468e3d51e5d62b296b7f0f205a76e985a29c9f9684ff162"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stoa-platform/stoactl/releases/download/v#{version}/stoactl_#{version}_linux_amd64.tar.gz"
      sha256 "ba60f43dfaa920e894c7247fbc26a742be0db413cc9544eab1618f23bd915378"
    end
    on_arm do
      url "https://github.com/stoa-platform/stoactl/releases/download/v#{version}/stoactl_#{version}_linux_arm64.tar.gz"
      sha256 "70426136e0a4fce1a43094d5bbf065c44b8e5e8f43dfe4e283b225c13795ef4f"
    end
  end

  # No zap stanza required
end
