# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoactl < Formula
  desc "GitOps-native CLI for STOA Platform"
  homepage "https://gostoa.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_amd64.tar.gz"
      sha256 "ecc211c6cac3c6dbb66542d23b938eeeb4b642d3b2d8555f370154dacb7a7527"

      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_arm64.tar.gz"
      sha256 "d62dab904d41369a1dc04304768ed59db86914883eaab20cb8ce7518a04ceb25"

      def install
        bin.install "stoactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_amd64.tar.gz"
      sha256 "50fe5f70c863d6798f07a47b5d0829c2624232de16d27280ab986c5896833726"
      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_arm64.tar.gz"
      sha256 "f54a065528a44bf11ffcdeb68f5e6f213fe7d85d5cd61e662c415c9c5fc0f57a"
      def install
        bin.install "stoactl"
      end
    end
  end

  test do
    system "#{bin}/stoactl", "version"
  end
end
