# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoactl < Formula
  desc "GitOps-native CLI for STOA Platform"
  homepage "https://gostoa.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_amd64.tar.gz"
      sha256 "a67992d49af9e557547cf7256cc7362a104b83046feeba222b586b115c875d11"

      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_arm64.tar.gz"
      sha256 "b87ccefb7aa218565c97656d0adfb0686bf5cc43b95496132082143d74f45436"

      def install
        bin.install "stoactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_amd64.tar.gz"
      sha256 "5e9fddcf19202078b773533b3a8ce4894a13c00cb13610abcebfb175604788cc"
      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_arm64.tar.gz"
      sha256 "cbf13c967d1a2a76003ca9b206fecc23def3af629d1d253539fb2cb3aa949b54"
      def install
        bin.install "stoactl"
      end
    end
  end

  test do
    system "#{bin}/stoactl", "version"
  end
end
