# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stoactl < Formula
  desc "GitOps-native CLI for STOA Platform"
  homepage "https://gostoa.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_amd64.tar.gz"
      sha256 "8e37bce7bd31f2a432847b96f5b2ba07604b64320ef2195b8e7f9ff3fc8fb456"

      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_darwin_arm64.tar.gz"
      sha256 "f13c9afae3c44ae1c0fa54f00ef9ab9dfb656eabb216f7d75a0da57c9fcbb45c"

      def install
        bin.install "stoactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_amd64.tar.gz"
      sha256 "c8d8e86d0f0e209203d045b50800683cb25cca7cb460379593fbf5546cc4d216"
      def install
        bin.install "stoactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stoa-platform/stoactl/releases/download/v0.1.0/stoactl_0.1.0_linux_arm64.tar.gz"
      sha256 "a0ba601ce8935fd9a11bc62ab2773e6138044b4ce13e274d11c061a71f3d463b"
      def install
        bin.install "stoactl"
      end
    end
  end

  test do
    system "#{bin}/stoactl", "version"
  end
end
